# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d44d6c80163a3e0bd2eb8009b7c8243d652a1e562b2919bd980bd695313f7bb7fc76bb0d46488acf7be08092028feada64eed7ee9ed2243a0e4e423d81ae429

test:
  secret_key_base: 5247e21a9a152431ee4a2567a39458c52baa1993a4ee2586db4e82d828c4eb26d937aa4cc88e163a17f26c24dc473e3080a093b87b3688d5a55bbce59cfa9214

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
